name: Build and (conditionally) Push n8n (ARM64)

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build and Push
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        run: |
          docker buildx create --use --name builder || docker buildx use builder
          docker buildx inspect --bootstrap

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build + Tag + Push (Makefile)
        run: |
          make login
          make build
          make tag
          make push
